In [1]:
# Data Processing 

# Importing Libraries

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Importing dataset

dataset = pd.read_csv("Data.csv")
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
# Initialize x variable

x = dataset.iloc[:,:-1].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [4]:
# Initialize y variable

y = dataset.iloc[:,3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [6]:
# Take care of missing data
from sklearn.preprocessing import Imputer

imputer = Imputer(missing_values='NaN',strategy='mean', axis=0)
imputer

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [8]:
imputer = imputer.fit(x[:,1:3])
imputer

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [10]:
x[:,1:3] = imputer.transform(x[:,1:3])
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [14]:
# Encoding categorical data
# Enconding the independent variable

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelEncoder_x = LabelEncoder()
x[:,0] = labelEncoder_x.fit_transform(x[:,0])
x[:,0]

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=object)

In [15]:
oneHotEncoder = OneHotEncoder(categorical_features=[0])
oneHotEncoder

OneHotEncoder(categorical_features=[0], dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [17]:
x=oneHotEncoder.fit_transform(x).toarray()
x

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.40000000e+01, 7.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        3.00000000e+01, 5.40000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        4.00000000e+01, 6.37777778e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.50000000e+01, 5.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        3.87777778e+01, 5.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.80000000e+01, 7.90000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        5.00000000e+01, 

In [22]:
# Encoding the dependent variable

labelEncoder_y = LabelEncoder()
y = labelEncoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int32)

In [27]:
# Splitting the dataset into trainset and testset

from sklearn.cross_validation import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)
print(y_train)
y_test

[0 1 0 0 1 1 0 1]


array([0, 1], dtype=int32)

In [28]:
#Feature scalling

from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()
x=sc_x.fit_transform(x)
x

array([[-1.22474487e+00,  1.22474487e+00, -6.54653671e-01,
        -6.54653671e-01,  7.58874362e-01,  7.49473254e-01],
       [ 8.16496581e-01, -8.16496581e-01, -6.54653671e-01,
         1.52752523e+00, -1.71150388e+00, -1.43817841e+00],
       [ 8.16496581e-01, -8.16496581e-01,  1.52752523e+00,
        -6.54653671e-01, -1.27555478e+00, -8.91265492e-01],
       [ 8.16496581e-01, -8.16496581e-01, -6.54653671e-01,
         1.52752523e+00, -1.13023841e-01, -2.53200424e-01],
       [ 8.16496581e-01, -8.16496581e-01,  1.52752523e+00,
        -6.54653671e-01,  1.77608893e-01,  6.63219199e-16],
       [-1.22474487e+00,  1.22474487e+00, -6.54653671e-01,
        -6.54653671e-01, -5.48972942e-01, -5.26656882e-01],
       [ 8.16496581e-01, -8.16496581e-01, -6.54653671e-01,
         1.52752523e+00,  0.00000000e+00, -1.07356980e+00],
       [-1.22474487e+00,  1.22474487e+00, -6.54653671e-01,
        -6.54653671e-01,  1.34013983e+00,  1.38753832e+00],
       [ 8.16496581e-01, -8.16496581e-01,  1.527

In [29]:
x_test = sc_x.transform(x_test)
x_test

array([[ 0.81649658, -0.81649658,  1.52752523, -0.65465367, -1.27555478,
        -0.89126549],
       [-1.22474487,  1.22474487, -0.65465367, -0.65465367, -0.25834021,
         0.29371249]])