In [9]:
# train_test_split Example

from sklearn.cross_validation import train_test_split
import numpy as np

x,y = np.arange(30).reshape((10,3)),np.arange(10)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [10]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=5)
x_train

array([[12, 13, 14],
       [21, 22, 23],
       [ 3,  4,  5],
       [ 0,  1,  2],
       [24, 25, 26],
       [18, 19, 20],
       [ 9, 10, 11]])