<a href="https://colab.research.google.com/github/PrimePy/DataScience/blob/master/Deep%2520Learning/Deep%2520Learning%2520with%2520pytorch/PyTorch%2520Fundamentals/1.P.yTorch-Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!python --version 

Python 3.6.9


In [3]:
!pip --version

pip 19.3.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)


In [7]:
import torch
print(torch.__version__)

1.4.0


In [9]:
# Default type is float32 or float64
torch.get_default_dtype()

torch.float32

In [10]:
tensor_arr = torch.Tensor([[1,2,3], [2,3,4]])
tensor_arr

tensor([[1., 2., 3.],
        [2., 3., 4.]])

In [11]:
torch.is_tensor(tensor_arr)

True

In [15]:
# Find the no of values available in tensor
torch.numel(tensor_arr)

6

In [16]:
# Easy way to initialize weight
tensor = torch.rand(3,3)
tensor

tensor([[0.1700, 0.6035, 0.0159],
        [0.3009, 0.7497, 0.0208],
        [0.6734, 0.0943, 0.8215]])

In [20]:
int_tensor = torch.tensor([1,2]).type(torch.IntTensor)
int_tensor

tensor([1, 2], dtype=torch.int32)

In [21]:
short_tensor = torch.ShortTensor([1,2])
short_tensor

tensor([1, 2], dtype=torch.int16)

In [23]:
float_tensor = torch.Tensor([1.0,2.0,3.0]).type(torch.half)
float_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [25]:
float_tensor = torch.Tensor([1.0,2.0,3.0])
float_tensor

tensor([1., 2., 3.])

In [26]:
tensor_fill = torch.full((3,6), fill_value=10)
tensor_fill

tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]])

In [27]:
tensor_ones = torch.ones((3,3), dtype=torch.int32)
tensor_ones

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [28]:
tensor_like = torch.zeros_like(tensor_ones)
tensor_like

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [29]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [30]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [0]:
i = torch.tensor([[1,2,3], [2,3,4]])
v = torch.tensor([3,4,5], dtype=torch.float32)

In [36]:
sparse_tensor = torch.sparse_coo_tensor(i, v, [1, 3])
sparse_tensor.data

RuntimeError: ignored

In [38]:
tensor = torch.rand(2,3)
tensor

tensor([[0.5028, 0.4189, 0.7284],
        [0.8796, 0.3241, 0.9470]])

In [41]:
tensor.fill_(10) # Inplace operation

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [42]:
new_tensor = tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [43]:
tensor.add_(3) # Inplace operation

tensor([[13., 13., 13.],
        [13., 13., 13.]])

In [44]:
x = torch.linspace(0.1, 10.0, 15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [45]:
chunk = torch.chunk(x, 3, 0)
chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [46]:
tensor1 = chunk[0]
tensor2 = chunk[1]
tensor3 = torch.tensor([3.0, 4.0, 5.0])
torch.cat((tensor1, tensor2, tensor3), 0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [48]:
tensor = torch.rand(3, 3)
tensor

tensor([[0.4832, 0.0751, 0.3285],
        [0.8253, 0.1344, 0.6760],
        [0.5580, 0.8297, 0.4659]])

In [49]:
tensor[0,1]

tensor(0.0751)

In [52]:
tensor.size()

torch.Size([3, 3])

In [51]:
tensor.view(9)

tensor([0.4832, 0.0751, 0.3285, 0.8253, 0.1344, 0.6760, 0.5580, 0.8297, 0.4659])

In [53]:
tensor.view((3,3))

tensor([[0.4832, 0.0751, 0.3285],
        [0.8253, 0.1344, 0.6760],
        [0.5580, 0.8297, 0.4659]])

In [55]:
tensor[2, 2] = 100
tensor

tensor([[4.8325e-01, 7.5086e-02, 3.2848e-01],
        [8.2532e-01, 1.3441e-01, 6.7600e-01],
        [5.5803e-01, 8.2975e-01, 1.0000e+02]])

In [56]:
tensor.shape

torch.Size([3, 3])

In [58]:
t = torch.unsqueeze(tensor, 2)
t

tensor([[[4.8325e-01],
         [7.5086e-02],
         [3.2848e-01]],

        [[8.2532e-01],
         [1.3441e-01],
         [6.7600e-01]],

        [[5.5803e-01],
         [8.2975e-01],
         [1.0000e+02]]])

In [59]:
t.shape

torch.Size([3, 3, 1])

In [60]:
torch.transpose(t, 0, 1)

tensor([[[4.8325e-01],
         [8.2532e-01],
         [5.5803e-01]],

        [[7.5086e-02],
         [1.3441e-01],
         [8.2975e-01]],

        [[3.2848e-01],
         [6.7600e-01],
         [1.0000e+02]]])

In [61]:
sort_tensor, sort_index = torch.sort(t)
sort_tensor

tensor([[[4.8325e-01],
         [7.5086e-02],
         [3.2848e-01]],

        [[8.2532e-01],
         [1.3441e-01],
         [6.7600e-01]],

        [[5.5803e-01],
         [8.2975e-01],
         [1.0000e+02]]])

In [62]:
sort_index

tensor([[[0],
         [0],
         [0]],

        [[0],
         [0],
         [0]],

        [[0],
         [0],
         [0]]])

In [63]:
torch.abs(t)

tensor([[[4.8325e-01],
         [7.5086e-02],
         [3.2848e-01]],

        [[8.2532e-01],
         [1.3441e-01],
         [6.7600e-01]],

        [[5.5803e-01],
         [8.2975e-01],
         [1.0000e+02]]])

In [64]:
rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))
add1 = rand1 + rand2
add1

tensor([[0.4098, 2.7718, 2.4735],
        [2.8841, 2.3846, 0.9424]])

In [65]:
add2 = torch.add(rand1, rand2)
add2

tensor([[0.4098, 2.7718, 2.4735],
        [2.8841, 2.3846, 0.9424]])

In [66]:
div = torch.div(add2, add2+0.3)
div

tensor([[0.5773, 0.9023, 0.8918],
        [0.9058, 0.8883, 0.7585]])

In [67]:
mul = torch.mul(div, 2)
mul

tensor([[1.1546, 1.8047, 1.7837],
        [1.8116, 1.7765, 1.5171]])

In [71]:
clamp = torch.clamp(mul, min=1.7, max=2)
clamp

tensor([[1.7000, 1.8047, 1.7837],
        [1.8116, 1.7765, 1.7000]])

In [75]:
t1 = torch.tensor([1,2])
t2 = torch.tensor([3,4])
dot_product = torch.dot(t1, t2)
dot_product

tensor(11)

In [76]:
matrix = torch.Tensor([[1,2,3], [2,3,4]])
vector = torch.Tensor([3,4,5])
matrix_vector = torch.mv(matrix, vector)
matrix_vector

tensor([26., 38.])

In [79]:
matrix2 = torch.Tensor([[1,2], [2,3], [3,4]])
mul = torch.mm( matrix, matrix2)
mul

tensor([[14., 20.],
        [20., 29.]])

In [80]:
torch.argmax(mul, dim=1)

tensor([1, 1])

In [81]:
torch.argmax(mul, dim=0)

tensor([1, 1])

In [83]:
torch.argmin(mul, dim=1)


tensor([0, 0])