<a href="https://colab.research.google.com/github/PrimePy/DataScience/blob/master/Deep%2520Learning/Deep%2520Learning%2520with%2520pytorch/PyTorch%2520Fundamentals/2.PyTorch-Tensor_vs_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Convert numpy array to pytorch tensor

In [0]:
import numpy as np
import torch

In [3]:
t = torch.rand(4, 3)
t

tensor([[0.8705, 0.5152, 0.1143],
        [0.6782, 0.6166, 0.3630],
        [0.4587, 0.9106, 0.1360],
        [0.1587, 0.1990, 0.5350]])

In [4]:
type(t)

torch.Tensor

In [5]:
t_array = t.numpy()
t_array

array([[0.87052953, 0.5152113 , 0.11434489],
       [0.67817074, 0.6165908 , 0.36299533],
       [0.45873946, 0.91058296, 0.136029  ],
       [0.15868098, 0.19902563, 0.53504586]], dtype=float32)

In [6]:
type(t_array)

numpy.ndarray

In [7]:
torch.is_tensor(t_array)

False

In [8]:
t[0,0] = 100
t

tensor([[100.0000,   0.5152,   0.1143],
        [  0.6782,   0.6166,   0.3630],
        [  0.4587,   0.9106,   0.1360],
        [  0.1587,   0.1990,   0.5350]])

In [9]:
t_array

array([[100.        ,   0.5152113 ,   0.11434489],
       [  0.67817074,   0.6165908 ,   0.36299533],
       [  0.45873946,   0.91058296,   0.136029  ],
       [  0.15868098,   0.19902563,   0.53504586]], dtype=float32)

In [11]:
arr_tensor = torch.from_numpy(t_array)
arr_tensor

tensor([[100.0000,   0.5152,   0.1143],
        [  0.6782,   0.6166,   0.3630],
        [  0.4587,   0.9106,   0.1360],
        [  0.1587,   0.1990,   0.5350]])

In [13]:
arr_tensor[0,0] = 1000
arr_tensor

tensor([[1.0000e+03, 5.1521e-01, 1.1434e-01],
        [6.7817e-01, 6.1659e-01, 3.6300e-01],
        [4.5874e-01, 9.1058e-01, 1.3603e-01],
        [1.5868e-01, 1.9903e-01, 5.3505e-01]])

In [14]:
t_array

array([[1.00000000e+03, 5.15211284e-01, 1.14344895e-01],
       [6.78170741e-01, 6.16590798e-01, 3.62995327e-01],
       [4.58739460e-01, 9.10582960e-01, 1.36029005e-01],
       [1.58680975e-01, 1.99025631e-01, 5.35045862e-01]], dtype=float32)

In [15]:
type(arr_tensor)

torch.Tensor

In [16]:
torch.is_tensor(arr_tensor)

True

In [17]:
arr_tensor[0] = 1
arr_tensor

tensor([[1.0000, 1.0000, 1.0000],
        [0.6782, 0.6166, 0.3630],
        [0.4587, 0.9106, 0.1360],
        [0.1587, 0.1990, 0.5350]])

In [18]:
t_array

array([[1.        , 1.        , 1.        ],
       [0.67817074, 0.6165908 , 0.36299533],
       [0.45873946, 0.91058296, 0.136029  ],
       [0.15868098, 0.19902563, 0.53504586]], dtype=float32)

In [21]:
np_array_one = np.array([4,5])

np_array_one = torch.as_tensor(np_array_one) 
np_array_one

tensor([4, 5])

In [22]:
arr = np_array_one.numpy()
arr

array([4, 5])

In [23]:
arr[1] = 9
arr

array([4, 9])

In [24]:
np_array_one

tensor([4, 9])

In [26]:
tensor = torch.tensor(np_array_one) # Copy won't created
tensor[1]= 78
tensor

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


tensor([ 4, 78])

In [27]:
np_array_one

tensor([4, 9])

In [30]:
torch.cuda.is_available()

False