<a href="https://colab.research.google.com/github/PrimePy/DataScience/blob/master/Deep%2520Learning/Deep%2520Learning%2520with%2520pytorch/PyTorch%2520Fundamentals/3.PyTorch-Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [10]:
tensor = torch.tensor([[1,2,3],[2,3,4],[3,4,5]], dtype=torch.float32)
tensor

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]])

In [3]:
tensor.requires_grad

False

In [4]:
tensor2 = torch.randn((3,3))
tensor2

tensor([[-1.4282,  0.3213, -1.0829],
        [ 1.5917,  0.4480,  2.5253],
        [ 0.4135,  1.1751,  0.4476]])

In [5]:
tensor2.requires_grad

False

In [11]:
tensor.requires_grad_()

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]], requires_grad=True)

In [12]:
print(tensor.grad)

None


In [13]:
print(tensor.grad_fn)

None


In [0]:
mul = tensor * tensor

In [15]:
mul.requires_grad

True

In [16]:
print(mul.grad) # No gradient

None


In [17]:
print(mul.grad_fn)

In [18]:
out= (tensor * tensor2).mean()
print(out)

tensor(2.0859, grad_fn=<MeanBackward0>)


In [19]:
print(out.grad)

None


In [0]:
out.backward() # Initialize the backward propagation

In [21]:
print(out.grad)

None


In [22]:
print(tensor.grad)

tensor([[-0.1587,  0.0357, -0.1203],
        [ 0.1769,  0.0498,  0.2806],
        [ 0.0459,  0.1306,  0.0497]])


In [24]:
print(tensor2.grad) # requires_grad = false

None


In [25]:
tensor3 = tensor *3
tensor3

tensor([[ 3.,  6.,  9.],
        [ 6.,  9., 12.],
        [ 9., 12., 15.]], grad_fn=<MulBackward0>)

In [26]:
with torch.no_grad(): # requires_grad automatically turned off with in the with block.
  new_tensor = tensor * 3
  print(new_tensor)
  print('new tensor = ', new_tensor.requires_grad)
  print('requires_grad for tensor = ', tensor.requires_grad)
  print('requires_grad for tensor2 = ', tensor2.requires_grad)

tensor([[ 3.,  6.,  9.],
        [ 6.,  9., 12.],
        [ 9., 12., 15.]])
new tensor =  False
requires_grad for tensor =  True
requires_grad for tensor2 =  False


In [0]:
def calculate(t):
  return t *2 

In [0]:
@torch.no_grad()
def calculate_with_no_grad(t):
  return t * 2

In [29]:
result = calculate(tensor)
result

tensor([[ 2.,  4.,  6.],
        [ 4.,  6.,  8.],
        [ 6.,  8., 10.]], grad_fn=<MulBackward0>)

In [30]:
result.requires_grad

True

In [31]:
result_with_no_grad = calculate_with_no_grad(tensor)
result_with_no_grad

tensor([[ 2.,  4.,  6.],
        [ 4.,  6.,  8.],
        [ 6.,  8., 10.]])

In [33]:
result_with_no_grad.requires_grad

False

In [34]:
with torch.no_grad(): # Without grad
  new = tensor * 2
  print(new)
  with torch.enable_grad(): # With grad 
    new= tensor * 3
    print(new)

tensor([[ 2.,  4.,  6.],
        [ 4.,  6.,  8.],
        [ 6.,  8., 10.]])
tensor([[ 3.,  6.,  9.],
        [ 6.,  9., 12.],
        [ 9., 12., 15.]], grad_fn=<MulBackward0>)


In [41]:
tensor_one = torch.tensor([[1,2,3], [2,3,4], [3,4,5]], dtype=torch.float32, requires_grad=True)
tensor_two = torch.tensor([[1,2,3], [2,3,4], [3,4,5]], dtype=torch.float32)
tensor_two.requires_grad_()

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]], requires_grad=True)

In [44]:
new = (tensor_one + tensor_two).mean()
print(new.requires_grad)

True


In [45]:
new.backward()
print(tensor_one.grad)

tensor([[0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111]])


In [46]:
print(tensor_two.grad)

tensor([[0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111]])


In [47]:
new = tensor_one.detach()
detach_new = (tensor_one * new).mean()
print(new.requires_grad)

False
