<a href="https://colab.research.google.com/github/PrimePy/DataScience/blob/master/Deep%2520Learning/Deep%2520Learning%2520with%2520pytorch/PyTorch%2520Fundamentals/4.PyTorch-Autograd_with_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
from torch.autograd  import Variable

In [9]:
var = Variable(torch.tensor([3], dtype=torch.float32))
var

tensor([3.])

In [10]:
var.requires_grad_()

tensor([3.], requires_grad=True)

In [0]:
w1 = Variable(torch.tensor([3], dtype=torch.float32))
w2 = Variable(torch.tensor([6], dtype=torch.float32))

In [0]:
new = (var + w1).mean()

In [14]:
new

tensor(6., grad_fn=<MeanBackward0>)

In [0]:
new.backward()

In [16]:
new.requires_grad

True

In [21]:
print(new.grad)

None


In [18]:
var.grad

tensor([1.])

In [20]:
print(w1.grad)

None
