# Pytorch

Replacement for numpy to use GPUs
Maximum flexibility and speed

## Tensor
Similar to ndarray.
Used to accelate the GPU.

In [2]:
from __future__ import print_function
import torch

x = torch.empty(5,5)
print(x)

tensor([[1.3563e-19, 1.3563e-19, 1.3563e-19, 1.3563e-19, 1.3563e-19],
        [1.3563e-19, 1.4587e-19, 3.8188e-05, 8.1546e-33, 1.3563e-19],
        [1.6114e-19, 5.1715e-11, 1.7615e+19, 4.7429e+30, 5.5272e+31],
        [7.5338e+28, 3.1892e-09, 8.0671e+17, 5.0761e+31, 4.2964e+24],
        [1.7753e+28, 1.3458e-14, 1.4588e-19, 4.9114e-14, 1.3556e-19]])


In [3]:
x = torch.rand(2,2)
print(x)

tensor([[0.4047, 0.3916],
        [0.0438, 0.0198]])


In [4]:
x = torch.zeros(2,2, dtype=torch.int)
print(x)

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)


In [5]:
x = torch.tensor([5,5,5])
print(x)

tensor([5, 5, 5])


In [6]:
x = x.new_ones(5,5, dtype=torch.int)
print(x)

x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)
tensor([[0.3610, 0.3762, 0.9928, 0.2045, 0.4367],
        [0.8609, 0.8601, 0.9074, 0.4532, 0.3909],
        [0.8420, 0.4883, 0.3988, 0.7553, 0.3052],
        [0.1141, 0.4339, 0.4039, 0.2375, 0.7023],
        [0.8625, 0.6305, 0.2103, 0.2672, 0.0315]])


In [7]:
print(x.size())

torch.Size([5, 5])


In [8]:
y = torch.rand(5,5, dtype=float)
print(x+y)

tensor([[1.2794, 1.1110, 1.3842, 0.4507, 1.4336],
        [1.6560, 1.8397, 1.6087, 0.6475, 0.4267],
        [1.1180, 0.9475, 1.0495, 0.8076, 1.1743],
        [0.7764, 0.4383, 0.9184, 0.4207, 0.7812],
        [1.1396, 0.9146, 1.0512, 0.4575, 0.5010]], dtype=torch.float64)


In [9]:
print(torch.add(x,y))

tensor([[1.2794, 1.1110, 1.3842, 0.4507, 1.4336],
        [1.6560, 1.8397, 1.6087, 0.6475, 0.4267],
        [1.1180, 0.9475, 1.0495, 0.8076, 1.1743],
        [0.7764, 0.4383, 0.9184, 0.4207, 0.7812],
        [1.1396, 0.9146, 1.0512, 0.4575, 0.5010]], dtype=torch.float64)


In [10]:
result = torch.empty(5,5)
torch.add(x,y, out=result)
print(result)

tensor([[1.2794, 1.1110, 1.3842, 0.4507, 1.4336],
        [1.6560, 1.8397, 1.6087, 0.6475, 0.4267],
        [1.1180, 0.9475, 1.0495, 0.8076, 1.1743],
        [0.7764, 0.4383, 0.9184, 0.4207, 0.7812],
        [1.1396, 0.9146, 1.0512, 0.4575, 0.5010]])


In [11]:
y.add_(x)
print(y)

tensor([[1.2794, 1.1110, 1.3842, 0.4507, 1.4336],
        [1.6560, 1.8397, 1.6087, 0.6475, 0.4267],
        [1.1180, 0.9475, 1.0495, 0.8076, 1.1743],
        [0.7764, 0.4383, 0.9184, 0.4207, 0.7812],
        [1.1396, 0.9146, 1.0512, 0.4575, 0.5010]], dtype=torch.float64)


In [12]:
print(y[1:2,:3])

tensor([[1.6560, 1.8397, 1.6087]], dtype=torch.float64)


In [13]:
o = torch.ones(4,4)
p = o.view(16)
print(p)
q = o.view(-1, 8)
print(q)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])


In [14]:
x = torch.empty(1)
print(x)
print(x.item())

tensor([3.9008e-36])
3.900775836214285e-36


In [15]:
print(torch.cuda.is_available())

False


In [16]:
# Numpy Bridge

a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
# Cpnerting numpy to tensor:

import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [19]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [20]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [21]:
y.grad_fn

In [22]:
y = y-3
print(y)

tensor([[0., 0.],
        [0., 0.]], grad_fn=<SubBackward0>)


In [23]:
y.grad_fn

In [26]:
z = y*y*3
out = z.mean()
print(z, out)

tensor([[0., 0.],
        [0., 0.]], grad_fn=<MulBackward0>) tensor(0., grad_fn=<MeanBackward0>)
