# Pytorch

Replacement for numpy to use GPUs
Maximum flexibility and speed

## Tensor
Similar to ndarray.
Used to accelate the GPU.

In [1]:
from __future__ import print_function
import torch

x = torch.empty(5,5)
print(x)

tensor([[2.5630e-12, 1.4586e-19, 8.2990e-33, 1.3563e-19, 1.3563e-19],
        [1.3563e-19, 1.3563e-19, 1.3563e-19, 1.3563e-19, 1.3563e-19],
        [1.4587e-19, 3.8188e-05, 8.1546e-33, 1.3563e-19, 1.6114e-19],
        [5.1715e-11, 1.7615e+19, 4.7429e+30, 5.5272e+31, 7.5338e+28],
        [3.1892e-09, 8.0671e+17, 5.0761e+31, 4.2964e+24, 1.7753e+28]])


In [2]:
x = torch.rand(2,2)
print(x)

tensor([[0.6074, 0.3805],
        [0.3735, 0.4850]])


In [3]:
x = torch.zeros(2,2, dtype=torch.int)
print(x)

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)
